language: go

services:
  - docker

go:
  - 1.9
  - "1.10"
  - 1.11
  - tip

before_install:
  - docker pull influxdb
  - docker run -p 8086:8086 -v $PWD:/var/lib/influxdb influxdb
script:
  - go test -v -covermode=count -coverprofile=coverage.out ./...
  - goveralls -coverprofile=coverage.out -service travis-ci -repotoken N10Aya4dYexJebU4hW6lmBPZChrOzjMpY